### ISSUE TITLE
Должно быть int

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework1Gas#2]
https://github.com/HelgaJava/git-homework1Gas/blob/2c4e7a25996effee5294350cb6af58eec56f54ab/src/Main.java#L16-L17

**Comment by HelgaJava** [comment]
Исправила на int. Но я не согласна. Именно в комментах я указала, почему использовала double. В реальной ситуации мы не оперируем целыми числами. Поэтому здесь как с деньгами: если целые, то в копейках. Если по топливу, тогда давайте считать в мл и т.д. Но даже в мл может быт дробь. Здесь все зависит от шкалы деления. Поэтому точка зрения так важна при проектировании ИС.

**Comment by coursar** [comment]
Ok
